---
- include: firewall.yml

- name: Create the persistent folder
  file:
    name: /docker/portainer
    state: directory

# tasks file for ansible-role-portainer
- name: Start portainer
  command: >
    docker service create 
        --name portainer 
        --publish 9000:9000 
        --constraint 'node.role == manager' 
        --mount type=bind,source=/docker/portainer,destination=/data
        portainer/portainer 
        -H tcp://{{ iputils_ip_external }}:2375
  when: 
    - inventory_hostname in groups['swarm_managers'][0]
